## 主配置文件 这里存放的是公共的配置信息
# 激活对应的环境的配置文件
spring:
 profiles: 
  active: dev

# Redis数据库索引（默认为0）
 redis:
  database: 0
# Redis服务器地址
  host: 154.8.141.51
# Redis服务器连接端口
  port: 6379
# Redis服务器连接密码（默认为空）
  password: zhsj201314
# 连接池最大连接数（使用负值表示没有限制）
  pool: 
   max-active: -1
# 连接池最大阻塞等待时间（使用负值表示没有限制）
   max-wait: -1
# 连接池中的最大空闲连接
   max-idle: 0
# 连接池中的最小空闲连接
   min-idle: 8
#连接超时时间（毫秒)
  timeout: 0